In [2]:
import numpy as np
a=[2,3,4,6,8]
data=np.array(a)
print(data)

[2 3 4 6 8]


In [3]:
d=np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [4]:
d

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [5]:
type(d)

numpy.ndarray

In [6]:
d1=np.array([[1,2,3],[2,4,5],[5,6,7]])

In [7]:
d1

array([[1, 2, 3],
       [2, 4, 5],
       [5, 6, 7]])

In [8]:
d1.shape

(3, 3)

In [10]:
data=np.arange(0,101)
print(data)


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [14]:
d=np.arange(0,100)
d
d2=d.reshape(10,10)
print(d2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [16]:
data3=np.linspace(0,8,20)
data3

array([0.        , 0.42105263, 0.84210526, 1.26315789, 1.68421053,
       2.10526316, 2.52631579, 2.94736842, 3.36842105, 3.78947368,
       4.21052632, 4.63157895, 5.05263158, 5.47368421, 5.89473684,
       6.31578947, 6.73684211, 7.15789474, 7.57894737, 8.        ])

In [18]:
d5=np.random.randint(0,20,size=(2,4))
d5

array([[ 9, 16,  7, 15],
       [ 2, 19, 10, 12]])

In [25]:
d6=np.ones((4,3),int)
d6
np.vstack([d6,d6*10])

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
d6=np.zeros((4,3),int)
d6


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
d6=np.ones((4,3),int)
d6
np.hstack([d6,d6*10])

array([[ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10]])

In [37]:
b=np.array([1,2,3,4])
c=np.array([2,3,4,5])
b**c

array([   1,    8,   81, 1024], dtype=int32)

In [39]:
b.any()

True

In [40]:
b.dot(c)

40

In [43]:
d1.T

array([[1, 2, 5],
       [2, 4, 6],
       [3, 5, 7]])

In [44]:
d1

array([[1, 2, 3],
       [2, 4, 5],
       [5, 6, 7]])

In [45]:
d1.max()

7

In [46]:
d1.min()

1

In [47]:
d1.sum()

35

In [48]:
d1.mean()

3.888888888888889